### ISSUE TITLE
Autostart the bat is not working (WPE, not Standalone)

### ISSUE THREAD

**Issue by alphe-lbp** [The-Kernel-Brothers/Windows-Pocket-Edition#2]
We need to add a way to autostart the bat file at startup for Windows Pocket Edition (not Standalone)

**Comment by Minionguyjpro** [comment]
This would be possible by copying it to the startup folder, but I think there are more reliable ways.

**Comment by alphe-lbp** [comment]
ill try that first

**Comment by Minionguyjpro** [comment]
Did you already add this feature? Otherwise I can do it

**Comment by Minionguyjpro** [comment]
This is done.
